config/routes.rb
MyApp::Application.routes.draw do
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  get "users/new"
  get "users/edit"

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/', :to => 'pages#home'
  match 'edit', :to => 'user#edit'
  
  
  

  root :to => 'pages#home'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.+\z/i
  
  validates :name, :presence => true, 
		   :length => { :maximum => 50 }
  validates :email, :presence => true, 
		    :format => { :with => email_regexp }, 
		    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true, 
		       :confirmation => true, 
		       :length => { :within => 6..40 }
  before_save :encrypt_password
  
  def has_password?(submitted_password)
     encrypted_password == encrypt(submitted_password)
  end
  
  private
    
    def encrypt_password
       self.salt =make_salt if new_record?
       self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
       secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
       secure_hash("#{Time.now.utc}--#{password}")
    end
    def secure_hash
       Digest::SHA2.hexdigest(string)
    end
    def self.authenticate(email, submitted_password)
       user = find_by_email(email)
       return nil if user.nil?
       return user if user.has_password?(submitted_password)
    end
    
    def self.authenticate_with_salt(id, cookie_salt)
       user = find_by_id(id)
       (user && user.salt) ? user : nil
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
   @title = "Contact"
  end

  def about
   @title = "About"
  end
  
  def help
   @title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title="Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
			     params[:session][:password])
    if user.nil?
       flash.now[:error] = "Invalid email/password combination"
       @title = "Sign in"
       render = 'new'
    else
       sign_in user
       redirect_back_or user
    end 
  end
  
  def destroy
     sign_out
     redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]

  def index
    @title = "All users"
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def edit
    @title = "Edit user"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to My App!"
      redirect_to @user
    else
       @title = "Sign up"
       render 'new'
    end
    
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
       @title = "Edit user"
       render 'edit'
    end
    
  end
  
  private
    def authenticate
       deny_access unless signed_in?
    end
    
    def correct_user
       @user = User.find(params[:id])
       redirect_to(root_path) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
      image_tag("chiara.png", :alt => "My App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def sign_in(user)
  cookies.permanent.signed[:remember_token] = [user.id, user.salt]
  self.current_user = user
end

def current_user=(user)
  @current_user = user
end

def current_user
  @current_user ||= user_from_remember_token
end

def sign_out
  cookies.delete(:remember_token)
  self.current_user = nil
end

def signed_in?
 !current_user.nil?
end

def current_user?(user)
 user == current_user
end

def deny_access
  redirect_to signin_path, :notice => "Please sign in to Access!"
end

def redirect_back_or(default)
   redirect_to(session[:return_to] || default)
   clear_return_to
end

private

  def user_from_remember_token
     User.authenticate_with_salt(*remember_token)
  end
  
  def remember_token
     cookies.signed[:remember_token] || [nil, nil]
  end

  def store_location
     session[:return_to] = request.fullpath
  end
  
  def clear_return_to
     session[:return_to] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
 <nav>
  <ul>
     <%= link_to "About", about_path %>
     <%= link_to "Contact", contact_path %>
  </ul>
 </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
 <% logo = image_tag("chiara.png", :alt => "My App", :class => "round") %>
 <%= link_to logo, root_path %>
 <nav class="round">
  <ul>
     <%= link_to "Home", root_path %>
     <!--% if signed_in?%-->
     <%= link_to "Users", users_path %>
     <%= link_to "Profile", current_user %>
     <%= link_to "Settings", edit_user_path(current_user) %>
     <!--% end %-->
     
     <%= link_to "Help", help_path %>
     <% if signed_in?%>
     <%= link_to "Sign out", signout_path, :method => :delete %>
     <% else %>
     <%= link_to "Sign in", signin_path %>
     <% end %>
  </ul>
 </nav>
</header>

app/views/layouts/_stylesheets.html.erb
     <!--[if lt IE 9]>
     <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
     <![end if]-->
     <%= stylesheet_link_tag    'bleprint/screen', :media => 'screen' %>
     <%= stylesheet_link_tag    'bleprint/print', :media => 'print' %>
     <!--[if lt IE8]><%= stylesheet_link_tag    'bleprint/ie' %><![endif]-->
     <%= stylesheet_link_tag    'custom', :media => 'screen' %>
     <%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
     <title>My App RoR</title>
     <%= csrf_meta_tags %>
     <%= render 'layouts/stylesheets' %>
   </head>
   <body>
     <div class="container">
       <%= render 'layouts/header' %>
       <section class="round">
          <%= flash.each do |key, value| %>
	      <div class="flash <%= key %>"><%= value %></div>
	  <% end %>    
	  <%= yield %>
       </section>
       <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
     </div>
   </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>About My App</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p> Contact Us</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>Get Help for Using My App</p>

app/views/pages/home.html.erb
<h1>Welcome to My App!</h1>
<p>This is the home page for My App!
</p>
<%= link_to "Sign up now!", new_user_path %>

app/views/shared/_error_messages.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@object.errors.count, "error") %> prohibited this user from being saved:</h2>
      <p> Verify following fields:</p>
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages',:object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up"%>
  </div>
<% end %>

app/views/users/_formedit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <% render 'shared/error_messages', :object => f.object%>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update"%>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/create.html.erb
<h1>Welcome in My App!</h1>

app/views/users/edit.html.erb
<h1>Sign up</h1>
<%= render 'formedit' %>

<%= link_to 'Back to Profile', current_user %>

app/views/users/index.html.erb
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, :size => 30 %>
      <%= link_to user.name, user %></td>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form' %>

<%= link_to 'Back to Home', root_path %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td>
      <h1>
        <%= gravatar_image_tag @user.email %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong><%= @user.name %><br />
      <strong>URL</strong><%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>